name: Build on macOS

on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: Install dependencies
      shell: bash
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip3 install wheel
        pip3 install meson
        pip3 install ninja
        brew install yasm nasm
    - name: configure
      shell: bash
      run: |
        export SDKROOT="$(xcrun --sdk macosx --show-sdk-path)"
        source venv/bin/activate
        bash scripts/apply-patches.sh
        bash scripts/build-deps.sh
        cmake -S . -B build -G 'Ninja'
        # FIXME
        sed -e 's/ -static$/ /' -e 's/ -static / /' build/build.ninja > build/build_fixed.ninja
        mv build/build_fixed.ninja build/build.ninja 
    - name: make
      shell: bash
      run: |
        export SDKROOT="$(xcrun --sdk macosx --show-sdk-path)"
        source venv/bin/activate
        (cd build && ninja)
